apiVersion: v1
kind: Pod
metadata:
  name: efs-test
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: efs-storage
          mountPath: /mnt/efs
  volumes:
    - name: efs-storage
      persistentVolumeClaim:
        claimName: efs-pvc
