apiVersion: v1
kind: Pod
metadata:
  name: app-using-efs
spec:
  containers:
    - name: app
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: efs-volume
          mountPath: /mnt/efs
  volumes:
    - name: efs-volume
      persistentVolumeClaim:
        claimName: efs-pvc
