apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizappsql-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quizappsql
  template:
    metadata:
      labels:
        app: quizappsql
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: quizapp
          image: 241533146625.dkr.ecr.us-east-1.amazonaws.com/quizapp-flask:v1.0.4
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: quizapp-config
            - secretRef:
                name: quizapp-secret
          # OPTIONAL: If your Flask app writes to /app/db or similar, use emptyDir
          volumeMounts:
            - name: sqlite-storage
              mountPath: /app/db
      # OPTIONAL: Use emptyDir so both replicas have isolated in-memory storage (non-persistent)
      volumes:
        - name: sqlite3-storage
          persistentVolumeClaim:
            claimName: sqlite3-pvc
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - quizappsql
                topologyKey: "kubernetes.io/hostname"
