apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlite-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlite
  template:
    metadata:
      labels:
        app: sqlite
    spec:
      containers:
        - name: sqlite
          image: nouchka/sqlite3
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: sqlite-data
              mountPath: /app/db
      volumes:
        - name: sqlite-data
          persistentVolumeClaim:
            claimName: sqlite-pvc
