apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "0.0.0.0/0"

  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
#############################################

# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
#     service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
#     service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "0.0.0.0/0"
#     service.beta.kubernetes.io/aws-load-balancer-internal: "ip"
#   labels:
#     app: nginx
# spec:
#   selector:
#     app: nginx
#   type: LoadBalancer
#   ports:
#     - port: 80
#       targetPort: 80
