apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
# ------------------------------------------
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: sqlite-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: gp2 # or gp3 or the default in your cluster
#   resources:
#     requests:
#       storage: 1Gi
