apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizapp-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quizapp
  template:
    metadata:
      labels:
        app: quizapp
    spec:
      containers:
        - name: quizapp
          image: 241533146625.dkr.ecr.us-east-1.amazonaws.com/quizapp-flask:main-8eae3da
<<<<<<< HEAD

=======
>>>>>>> ee400454eac39dfad9383da5307f8ad5d07059a9
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: sqlite-storage
              mountPath: /app/data
          env:
            - name: FLASK_ENV
              value: "production"
            - name: SQLALCHEMY_DATABASE_URI
              value: "sqlite:////app/data/db.sqlite"
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: sqlite-pvc

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - quizapp
                topologyKey: "kubernetes.io/hostname"
