apiVersion: v1
kind: Service
metadata:
  name: quizapp-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  selector:
    app: quizapp
  ports:
    - port: 80
      targetPort: 5000
